### ISSUE TITLE
MultiAddressWrite能否增加addString(String address, String data)

### ISSUE THREAD

**Issue by winhkey** [xingshuangs/iot-communication#11]
1. MultiAddressWrite里只有addByte(String address, byte[] data)方法，如果只把字符串的字节数组传进去，这个方法里与writeString方法里关于byte[]的处理是有区别的，writeString多了这行代码
requestItem.setByteAddress(requestItem.getByteAddress() + offset);
2. writeString里默认字符串是gb2312，是s7不支持utf-8么？
3. 用modbus如何跟s7一样批量读写？

**Comment by winhkey** [comment]
@xingshuangs 读非西门子的plc modbus，输入寄存器大于125个报错了

**Comment by xingshuangs** [comment]
modbus协议中约束了读取范围
![image](https://github.com/xingshuangs/iot-communication/assets/16301303/e9168654-a4c2-424a-9072-4e9f16d5805a)

**Comment by winhkey** [comment]
好吧，我看怎么分段读吧，多谢耐心回答

**Comment by winhkey** [comment]
还有两个问题
1. modbus连续地址怎么批量写
2. BA_DC读字符串xbj03的结果是bx0j 3x，还要自己再转一次

**Comment by xingshuangs** [comment]
1. modbus连续地址批量读，可以按指定大小进行分割，然后重新组装；
2. 字符串读取和BA_DC没有任何关系，字符串就按正常的字节顺序进行解析；

**Comment by winhkey** [comment]
就是说不管哪种EByteBuffFormat，字符串都是一样的，要自己处理对吧

**Comment by winhkey** [comment]
大小端boolean littleEndian和EByteBuffFormat是两个不同的东西么？

**Comment by xingshuangs** [comment]
EByteBuffFormat专门针对4字节数据的排序
