### ISSUE TITLE
再请教一个多线程读写modbus的问题

### ISSUE THREAD

**Issue by winhkey** [xingshuangs/iot-communication#12]
多线程读写modbus会不会有问题，是否需要专门用一个队列去读写，如果需要的话对于请求超时，队列阻塞有什么好的建议么

**Comment by xingshuangs** [comment]
1. 多线程没有问题，每次读写都有锁进行保护，保证数据准确，不需要队列读写
2. 阻塞要先排查下原因，如果是网络问题，那就没办法了，内部支持断线重连

**Comment by winhkey** [comment]
好的多谢

Oscura ***@***.***> 于2023年11月1日周三 09:39写道：
