### ISSUE TITLE
S7读写1200时发现读写不一致的问题

### ISSUE THREAD

**Issue by winhkey** [xingshuangs/iot-communication#13]
我每次写完一组点位表立刻再读一遍，然后判断两边数据一致就认为写成功了，否则就报错
现在一个新项目里发现经常出现读到的值不是本次写入的值，我用wireshark抓包看到写入都是成功的，下一步该如何定位是plc程序的问题还是我这里的问题
这是抓的包
[3.pcapng.zip](https://github.com/xingshuangs/iot-communication/files/13405735/3.pcapng.zip)
这是写入的值
<img width="287" alt="image" src="https://github.com/xingshuangs/iot-communication/assets/4877808/8e4a9a99-2e8f-40c2-97b0-cb40fce5c582">
这是读到的值与写入值不一致
<img width="478" alt="image" src="https://github.com/xingshuangs/iot-communication/assets/4877808/76825df3-3987-49fc-a918-2baa4a092868">

**Comment by winhkey** [comment]
刚才确认过了，抓包显示写成功，但是对方监控值没变化，这是什么原因啊？

**Comment by xingshuangs** [comment]
你这个地址还有别的途径可以进行修改
例如你的地址也给外部触摸屏使用，那么就存在触摸屏一直覆盖你写入的值
或者PLC程序不停修改这个地址，你写入的值一直被覆盖

**Comment by winhkey** [comment]
> 你这个地址还有别的途径可以进行修改 例如你的地址也给外部触摸屏使用，那么就存在触摸屏一直覆盖你写入的值 或者PLC程序不停修改这个地址，你写入的值一直被覆盖

确认过了，plc只读，没有覆盖

**Comment by winhkey** [comment]
> 你这个地址还有别的途径可以进行修改 例如你的地址也给外部触摸屏使用，那么就存在触摸屏一直覆盖你写入的值 或者PLC程序不停修改这个地址，你写入的值一直被覆盖

另外还有个问题，我用MultiAddressRead读指定的几个地址，但是从抓包来看，实际还是从头到尾读了完整的DB块

**Comment by xingshuangs** [comment]
> 确认过了，plc只读，没有覆盖

之前遇到过由于触摸屏和程序读写的地址是同一个，导致程序经常写不进数据

**Comment by xingshuangs** [comment]
> 另外还有个问题，我用MultiAddressRead读指定的几个地址，但是从抓包来看，实际还是从头到尾读了完整的DB块

MultiAddressRead得看你怎么使用了，它可以读取不连续的多地址，可以是不同区的数据，你若都读同一个DB块，那也是可以的

**Comment by winhkey** [comment]
s7是支持多连接的，PLCNetwork里是不是可以对每个连接单独加锁而不是用全局锁

**Comment by xingshuangs** [comment]
> s7是支持多连接的，PLCNetwork里是不是可以对每个连接单独加锁而不是用全局锁

plc是支持多个连接，但是S7PLC对象只是一个客户端链接，没法多连接
