### ISSUE TITLE
Comminication over Modbus Gate

### ISSUE THREAD

**Issue by Little-Cat** [xingshuangs/iot-communication#2]
Hi. How i can communicate with my device over Modbus Gate? I defined unitId for ModbusTcp object when it was created buţ it can`t work. I resived same data for different unitId. My unitId for my devices for example 5,10,15. I defined unitId6 but i can get data!! Help please. Thanks.

**Comment by xingshuangs** [comment]
I haven't tried Modbus Gate. ModbusTcp is connected based on unitId. Please confirm the unitId of your device first.
