### ISSUE TITLE
给的例子中string可以写count，但是在代码中只能byte能写count。

### ISSUE THREAD

**Issue by lovely-xin** [xingshuangs/iot-communication#4]
你好，给的例子中string可以写count，但是在代码中只能byte能写count，比如我现在string长度是60，请问我注解应该怎么写？

**Comment by xingshuangs** [comment]
v1.2.7中string是不可以写count，只有byte支持，下一个版本支持string添加count
github中master是最新版，比v1.2.7新，如果你想使用可以自行拉最新代码，打包

**Comment by CodeWriter-Lovely** [comment]
感谢，现在又发现了一个新的问题，writeString写入到PLC后，1200PLC无法处理此字符串，PLC定义string[60]。我看了下代码
`public void writeString(String address, String data) {
        if (data.length() > 253) {
            throw new IllegalArgumentException("data字符串参数过长，超过253");
        }
        byte[] dataBytes = data.getBytes(StandardCharsets.US_ASCII);
        byte[] tmp = new byte[2 + dataBytes.length];
        tmp[0] = (byte) 0xFE;  //这里长度是254
        tmp[1] = ByteUtil.toByte(dataBytes.length);
        System.arraycopy(dataBytes, 0, tmp, 2, dataBytes.length);
        this.writeByte(address, tmp);
    }`
是不是PLC string的长度要定义要在254以上才可以使用？

**Comment by xingshuangs** [comment]
String提供了最大256个字节，前两个字节分别表示字节中最大的字符数和当前的字符数
一般我遇到的都是string类型，它总字节大小是256，对应最大字符数254
如果是string[60]，它总字节大小是62，对应最大字符数60
我这个库确实没法支持string[60]这种情况，需要优化下
![image](https://user-images.githubusercontent.com/16301303/236624946-7e150400-e51c-4e0f-9e9d-8b831478877d.png)
