### ISSUE TITLE
可以获取PLC内的符号表吗

### ISSUE THREAD

**Issue by ilovexyz** [xingshuangs/iot-communication#5]
您好，这个库可以获取PLC内的符号表吗？我想枚举内部符号表的变量名信息

**Comment by xingshuangs** [comment]
暂不支持，目前只能是地址寻址
![image](https://user-images.githubusercontent.com/16301303/236625423-80e20461-2bfa-4262-9d70-a3c0942ee326.png)
下面的符号寻址还不知道怎么处理
![image](https://user-images.githubusercontent.com/16301303/236625309-6d404c25-a262-44a5-b022-d3853a36dd4c.png)

**Comment by ilovexyz** [comment]
好的，谢谢，我再找找有没有别的方法
