### ISSUE TITLE
readString方法读取到中文字符乱码，怎么解决

### ISSUE THREAD

**Issue by clownSong** [xingshuangs/iot-communication#9]

**Comment by xingshuangs** [comment]
S7读字符串，默认编码为ASCII，如果中文乱码，目前可以先将返回的字符串按照ASCII编码转换为字节数组，然后再字节数组按照UTF-8编码重新转换为新字符串；

**Comment by xingshuangs** [comment]
新版本已发布v1.4.2，可以采用新版本的readString
